# Generated by Django 5.1.3 on 2024-11-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
