# Generated by Django 5.1.3 on 2024-11-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0002_alter_menuitem_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
