# Generated by Django 5.1.3 on 2024-11-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0008_orderdetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivered_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="menu_items",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ordered_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="prepared_at",
        ),
        migrations.AddField(
            model_name="order",
            name="menu_item",
            field=models.ForeignKey(
                default=0.0,
                on_delete=django.db.models.deletion.CASCADE,
                to="canteen.menuitem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Confirmed"), ("R", "Prepared")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
