# Generated by Django 5.1.3 on 2024-11-26 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0009_remove_order_delivered_at_remove_order_menu_items_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="menu_item",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="canteen.order",
            ),
        ),
    ]
