# Generated by Django 5.1.3 on 2024-11-26 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0010_remove_order_menu_item_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="OrderDetail",
        ),
    ]
