# Generated by Django 5.1.3 on 2024-11-26 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0011_order_created_at_delete_orderdetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="created_at",
            new_name="ordered_at",
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="menu_items",
            field=models.ManyToManyField(
                through="canteen.OrderItem", to="canteen.menuitem"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="prepared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("prepared", "Prepared"),
                    ("delivered", "Delivered"),
                ],
                default="ordered",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="canteen.order"
            ),
        ),
    ]
