# Generated by Django 5.1.3 on 2024-11-26 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0012_rename_created_at_order_ordered_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="menu_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="canteen.menuitem",
            ),
        ),
    ]
