# Generated by Django 5.1.3 on 2024-11-26 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0013_alter_cartitem_menu_item"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Canteen",
        ),
    ]
