# Generated by Django 5.1.3 on 2024-11-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0015_canteen_remove_order_menu_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("prepared", "Prepared"),
                    ("delivered", "Delivered"),
                    ("confirmed", "Confirmed"),
                ],
                default="ordered",
                max_length=10,
            ),
        ),
    ]
